import { apiRequest } from "@/lib/api-client";
import type {
  BrandKit,
  CompanyAnalysis,
  CompanyAnalysisInput,
  GenerationProgress,
  LayoutPreview,
  PersonalizationCapabilities,
  PersonalizationConfig,
  PersonalizationState,
  PreviewBatch,
  ReferenceTemplatesResult,
} from "@/types/domain";

// Hyper-personalized campaigns (ADR-0011). Authorization is enforced by the
// server and the database; the UI only mirrors it to hide controls.

function campaignPath(workspaceId: string, campaignId: string, path = "") {
  return `/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/personalization${path}`;
}

export function newBatchId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now().toString(16)}-0000-4000-8000-${Math.random().toString(16).slice(2, 14).padEnd(12, "0")}`;
}

export async function getPersonalizationCapabilities(workspaceId: string) {
  const path = `/api/v1/workspaces/${workspaceId}/personalization/capabilities`;
  return (await apiRequest<PersonalizationCapabilities>(path)).data;
}

export async function getPersonalization(workspaceId: string, campaignId: string) {
  return (await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId))).data;
}

export async function savePersonalization(
  workspaceId: string,
  campaignId: string,
  payload: { config: PersonalizationConfig; expected_version?: number | null },
) {
  return (
    await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId), {
      method: "PUT",
      body: JSON.stringify(payload),
    })
  ).data;
}

// `batchId` is generated by the caller so a retried request returns the same
// batch instead of spending more of the daily sample budget.
export async function createPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
  payload: { batch_id: string; audience_member_ids: [string] },
) {
  return (
    await apiRequest<PreviewBatch>(campaignPath(workspaceId, campaignId, "/previews"), {
      method: "POST",
      body: JSON.stringify(payload),
    })
  ).data;
}

export async function getLatestPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
) {
  return (
    await apiRequest<PreviewBatch | null>(
      campaignPath(workspaceId, campaignId, "/previews/latest"),
    )
  ).data;
}

export async function getPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
  batchId: string,
) {
  return (
    await apiRequest<PreviewBatch>(campaignPath(workspaceId, campaignId, `/previews/${batchId}`))
  ).data;
}

export async function approvePersonalization(
  workspaceId: string,
  campaignId: string,
  payload: { batch_id: string; config_digest: string },
) {
  return (
    await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId, "/approve"), {
      method: "POST",
      body: JSON.stringify(payload),
    })
  ).data;
}

export async function getGenerationProgress(workspaceId: string, campaignId: string) {
  return (
    await apiRequest<GenerationProgress>(campaignPath(workspaceId, campaignId, "/progress"))
  ).data;
}

// --- AI authoring (ADR-0016). These spend model tokens, so they are POSTs that
// api-client never retries; the caller decides when to try again. ---

export async function analyzeCompany(
  workspaceId: string,
  campaignId: string,
  input: CompanyAnalysisInput,
) {
  return (
    await apiRequest<CompanyAnalysis>(campaignPath(workspaceId, campaignId, "/company-analysis"), {
      method: "POST",
      body: JSON.stringify(input),
    })
  ).data;
}

export async function previewEmailLayout(
  workspaceId: string,
  campaignId: string,
  payload: {
    brand: BrandKit;
    company_name?: string;
    site_url?: string | null;
    cta_label?: string | null;
  },
) {
  return (
    await apiRequest<LayoutPreview>(
      campaignPath(workspaceId, campaignId, "/email-layout-preview"),
      { method: "POST", body: JSON.stringify(payload) },
    )
  ).data;
}

// `follow_up_count` is only used when the sequence has no emails yet;
// `instructions` only when regenerating one email (scope STEP).
export async function generateReferenceTemplates(
  workspaceId: string,
  campaignId: string,
  payload: {
    scope: "ALL" | "STEP";
    step_id?: string;
    follow_up_count?: number;
    instructions?: string;
  },
) {
  return (
    await apiRequest<ReferenceTemplatesResult>(
      campaignPath(workspaceId, campaignId, "/reference-templates"),
      { method: "POST", body: JSON.stringify(payload) },
    )
  ).data;
}
