import { apiRequest } from "@/lib/api-client";
import type {
  GenerationProgress,
  PersonalizationCapabilities,
  PersonalizationConfig,
  PersonalizationState,
  PreviewBatch,
} from "@/types/domain";

// Hyper-personalized campaigns (ADR-0011). Authorization is enforced by the
// server and the database; the UI only mirrors it to hide controls.

function campaignPath(workspaceId: string, campaignId: string, path = "") {
  return `/api/v1/workspaces/${workspaceId}/campaigns/${campaignId}/personalization${path}`;
}

export function newBatchId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now().toString(16)}-0000-4000-8000-${Math.random().toString(16).slice(2, 14).padEnd(12, "0")}`;
}

export async function getPersonalizationCapabilities(workspaceId: string) {
  const path = `/api/v1/workspaces/${workspaceId}/personalization/capabilities`;
  return (await apiRequest<PersonalizationCapabilities>(path)).data;
}

export async function getPersonalization(workspaceId: string, campaignId: string) {
  return (await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId))).data;
}

export async function savePersonalization(
  workspaceId: string,
  campaignId: string,
  payload: { config: PersonalizationConfig; expected_version?: number | null },
) {
  return (
    await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId), {
      method: "PUT",
      body: JSON.stringify(payload),
    })
  ).data;
}

// `batchId` is generated by the caller so a retried request returns the same
// batch instead of spending more of the daily sample budget.
export async function createPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
  payload: { batch_id: string; audience_member_ids?: string[] },
) {
  return (
    await apiRequest<PreviewBatch>(campaignPath(workspaceId, campaignId, "/previews"), {
      method: "POST",
      body: JSON.stringify(payload),
    })
  ).data;
}

export async function getLatestPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
) {
  return (
    await apiRequest<PreviewBatch | null>(
      campaignPath(workspaceId, campaignId, "/previews/latest"),
    )
  ).data;
}

export async function getPersonalizationPreviews(
  workspaceId: string,
  campaignId: string,
  batchId: string,
) {
  return (
    await apiRequest<PreviewBatch>(campaignPath(workspaceId, campaignId, `/previews/${batchId}`))
  ).data;
}

export async function approvePersonalization(
  workspaceId: string,
  campaignId: string,
  payload: { batch_id: string; config_digest: string },
) {
  return (
    await apiRequest<PersonalizationState>(campaignPath(workspaceId, campaignId, "/approve"), {
      method: "POST",
      body: JSON.stringify(payload),
    })
  ).data;
}

export async function getGenerationProgress(workspaceId: string, campaignId: string) {
  return (
    await apiRequest<GenerationProgress>(campaignPath(workspaceId, campaignId, "/progress"))
  ).data;
}
